// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szmgjdkrnpypsxlemyqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6bWdqZGtybnB5cHN4bGVteXFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NDY3MjgsImV4cCI6MjA2ODMyMjcyOH0.O6sF_KmzE-c5_lpiLgWVkYZFyA-Cbj-vFN-HZ_mJukM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});